server:
  port: 8080

spring:
  application:
    name: crm
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

openai:
  api:
    model: gpt-4-turbo
    url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI_KEY}
